# -*- coding: utf-8 -*-
"""Configuration file for the player."""
GBA_BASE_FRAMERATE = 59.97
TICKS_PER_SECOND = 75

BASE_FREQUENCY = 7040
SEMITONE_RATIO = 2**(1 / 12)

PSG_WAVEFORM_FREQUENCY = 8372
PSG_WAVEFORM_VOLUME = 0.31 # 0 <= x <= 1
PSG_WAVEFORM_SIZE = 32

PSG_SQUARE_VOLUME = 0.25 # 0 <= x <= 1
PSG_SQUARE_FREQUENCY = 7040
PSG_SQUARE_SIZE = 32

PSG_NOISE_VOLUME = 0.25 # 0 <= x <= 1
PSG_NOISE_SAMPLES = 4
PSG_NOISE_NORMAL_SIZE = 32767 // 2
PSG_NOISE_METALLIC_SIZE = 127

SHOW_PROCESSOR_EXECUTION = False
SHOW_FMOD_EXECUTION = False

PLAYBACK_FRAMERATE = GBA_BASE_FRAMERATE
PLAYBACK_SPEED = GBA_BASE_FRAMERATE / PLAYBACK_FRAMERATE
TRANSPOSE = 0
CHANNEL_WIDTH = 17
VOLUME = 255
DEFAULT_MIXER = 0x0094F800
MAXIMUM_NOTES = 32

# 0th bit - volume
# 1st bit - panning
# 2nd bit - notes
# 3rd bit - ticks

DISPLAY = 0b1111
