# -*- coding: utf-8 -*-
"""Configuration file for the player."""
GBA_BASE_FRAMERATE = 59.97

BASE_FREQUENCY = 7040
SEMITONE_RATIO = 2**(1 / 12)

WAVEFORM_FREQUENCY = 8372
WAVEFORM_VOLUME = 0.31
WAVEFORM_SIZE = 32

PSG_VOLUME = 0.25

SHOW_PROCESSOR_EXECUTION = False
SHOW_FMOD_EXECUTION = False
DISPLAY_NOTES = False
PLAYBACK_FRAMERATE = GBA_BASE_FRAMERATE * 2
PLAYBACK_SPEED = GBA_BASE_FRAMERATE / PLAYBACK_FRAMERATE
TRANSPOSE = 0
TICKS_PER_SECOND = 75
